config/routes.rb
Rails.application.routes.draw do
  get 'offer/index'

  get 'offer/search'

  get 'offer/create'

  get 'home/index'

  root 'offer#index'

end

app/models/company.rb
class Company
  include Mongoid::Document
  field :_id,         type: Integer
  field :name,        type: String
  field :short_pitch, type: String
  field :description, type: String
  field :logo_url,    type: String
  field :website_url, type: String
  field :created_at,  type: Date
  field :updated_at,  type: Date

  has_many :offers, class_name: "Offer", inverse_of: :company

  def self.with_tags(tags)
    self.collection.find(
      {'_id':{"$in":Offer.with_tags(tags).distinct('company_id')}}
    )
  end
end

app/models/offer.rb
class Offer
  include Mongoid::Document
  field :_id,                 type: Integer
  field :city,                type: String
  field :company_id,          type: Integer
  field :country_code,        type: String
  field :country_name,        type: String
  field :currency_code,       type: String
  field :expires_at,          type: Date
  field :main_requirements,   type: String
  field :nice_to_have,        type: String
  field :perks,               type: String
  field :first_published_at,  type: Date
  field :referral_value,      type: String
  field :relocation_paid,     type: Mongoid::Boolean
  field :role_description,    type: String
  field :salary_low,          type: Integer
  field :salary_high,         type: Integer
  field :title,               type: String
  field :work_from_home,      type: Mongoid::Boolean
  field :created_at,          type: Date
  field :updated_at,          type: Date
  field :type,                type: String
  field :remote,              type: Mongoid::Boolean
  field :tags,                type: Array
  field :url,                 type: String

  belongs_to :company, class_name: "Company", inverse_of: :offers

  #common queries
  scope :with_tags, -> (tags) { all_in(:tags => tags) }

  def self.get_tags_count
    #self.collection.aggregate([
    #  {"$group"=>{"_id"=>"$tags","c"=>{"$sum"=>1}}},
    #  {"$unwind":"$_id"},
    #  {"$group":{"_id":"$_id","c":{"$sum":"$c"}}},{"$sort":{"c":-1}}
    #])
    self.collection.aggregate([ 
      {"$unwind":"$tags"}, 
      {"$group"=>{"_id"=>"$tags","c"=>{"$sum"=>1}}},
      {"$sort":{"c":-1}} 
    ])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def index
    @company_count = Company.count
    @tags = Offer.get_tags_count
  end
end

app/controllers/offer_controller.rb
class OfferController < ApplicationController
  def search
    @companies = Company.with_tags(params[:tags].split(","))
  end

  def create
  end

  before_filter proc { |controller| 
    (controller.action_has_layout = false) if controller.request.xhr? 
  }
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offer_helper.rb
module OfferHelper
end

app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                Startupstack
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <div class="container">
        <div class="row header-info">
            <div class="col-xs-2">
                <%= image_tag "logo.png" %>
            </div>
        </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StartupstackClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
    <%= render 'layouts/header' %>
    <div id="main-container">
        <%= yield %>
    </div>
    <div id="response-block"></div>
    <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/offer/create.html.erb
<h1>Offer#create</h1>
<p>Find me in app/views/offer/create.html.erb</p>

app/views/offer/index.html.erb
<div class="container">
    <div class="row">
        <h1>Find companies that use your favorite language & technologies</h1>
    </div>
    <div class="row">
        <div class="counter">
            <span><%= @company_count %></span> companies are waiting for you
        </div>
    </div>
    <div class="row">
    <%= form_tag(offer_search_path, method:"get",remote: true, id:"search-form") do %>
        <div id="tag-select">
            <ul>
                <% @tags.each do |tag|  %>
                    <% if tag[:c] > 5%>
                        <li title="<%= tag[:c]%> offers"><%= tag[:_id] %></li>
                    <% end %>
                <% end %>
            </ul>
        </div>
        <%= submit_tag("Find my dream company", name:nil, class:"search-button")%>
    </div>
    <% end %>
</div>

app/views/offer/search.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-offset-2 col-md-8 col-md-suffix-2">
            <h4 class="result-message"><span><%= pluralize(@companies.count,"company") %></span> to follow your dream</h4>
        </div>
    </div>
    <div class="row offer-item">
        <% @companies.each do |company| %>
            <div class="center-block col-xs-12 col-lg-3 col-md-3 col-sm-6 img-responsive">
                <% #TODO move this to helper %>
                <%= link_to image_tag(company[:logo_url],title: company[:name] + ' - ' + company[:short_pitch]), company[:website_url]  %>
            </div>
        <% end %>
    </div>
</div>